// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BrandLogo: typeof import('./src/components/images/BrandLogo.vue')['default']
    CategoryFilter: typeof import('./src/components/CategoryFilter.vue')['default']
    ICarbonLogout: typeof import('~icons/carbon/logout')['default']
    ICarbonMenu: typeof import('~icons/carbon/menu')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    ILucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    ILucideBookOpen: typeof import('~icons/lucide/book-open')['default']
    ILucideCheckCircle: typeof import('~icons/lucide/check-circle')['default']
    ILucideCpu: typeof import('~icons/lucide/cpu')['default']
    ILucideFileCheck: typeof import('~icons/lucide/file-check')['default']
    ILucideGraduationCap: typeof import('~icons/lucide/graduation-cap')['default']
    ILucideMessageCircle: typeof import('~icons/lucide/message-circle')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    ILucideStar: typeof import('~icons/lucide/star')['default']
    ILucideTarget: typeof import('~icons/lucide/target')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    IMdiFacebook: typeof import('~icons/mdi/facebook')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiGoogle: typeof import('~icons/mdi/google')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    ISimpleIconsSupabase: typeof import('~icons/simple-icons/supabase')['default']
    ISimpleIconsVuedotjs: typeof import('~icons/simple-icons/vuedotjs')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    ToolCard: typeof import('./src/components/ToolCard.vue')['default']
    VButton: typeof import('./src/components/VButton.vue')['default']
    VIconButton: typeof import('./src/components/VIconButton.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VLabel: typeof import('./src/components/VLabel.vue')['default']
    VPasswordInput: typeof import('./src/components/VPasswordInput.vue')['default']
  }
}

export { }
