// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BrandLogo: typeof import('./src/components/images/BrandLogo.vue')['default']
    CategoryFilter: typeof import('./src/components/CategoryFilter.vue')['default']
    DynamicInputForm: typeof import('./src/components/DynamicInputForm.vue')['default']
    ICarbonLogout: typeof import('~icons/carbon/logout')['default']
    ICarbonMenu: typeof import('~icons/carbon/menu')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    ILucideAlertCircle: typeof import('~icons/lucide/alert-circle')['default']
    ILucideArrowLeft: typeof import('~icons/lucide/arrow-left')['default']
    ILucideCheckCircle: typeof import('~icons/lucide/check-circle')['default']
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    ILucideCopy: typeof import('~icons/lucide/copy')['default']
    ILucideLightbulb: typeof import('~icons/lucide/lightbulb')['default']
    ILucideLoader2: typeof import('~icons/lucide/loader2')['default']
    ILucideMessageCircle: typeof import('~icons/lucide/message-circle')['default']
    ILucidePlus: typeof import('~icons/lucide/plus')['default']
    ILucideSend: typeof import('~icons/lucide/send')['default']
    ILucideSettings: typeof import('~icons/lucide/settings')['default']
    ILucideStar: typeof import('~icons/lucide/star')['default']
    ILucideTrash2: typeof import('~icons/lucide/trash2')['default']
    ILucideUser: typeof import('~icons/lucide/user')['default']
    ISimpleIconsSupabase: typeof import('~icons/simple-icons/supabase')['default']
    ISimpleIconsVuedotjs: typeof import('~icons/simple-icons/vuedotjs')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    ToolCard: typeof import('./src/components/ToolCard.vue')['default']
    UniversalChatInterface: typeof import('./src/components/UniversalChatInterface.vue')['default']
    VButton: typeof import('./src/components/VButton.vue')['default']
    VIconButton: typeof import('./src/components/VIconButton.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VLabel: typeof import('./src/components/VLabel.vue')['default']
    VPasswordInput: typeof import('./src/components/VPasswordInput.vue')['default']
  }
}

export { }
